name: 'Automated Research Pipeline'

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0 6 * * 1' # Runs every Monday at 06:00 UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the Research Pipeline Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY || '' }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY || '' }}
        run: python scripts/run_pipeline.py
